version: '3.3'
services:
  redis:
    command:
      - "redis-server"
      - "--loglevel"
      - "debug"
    image: "redis:7.0.8"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:10.4"
    environment:
      POSTGRES_USER: centerboard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: centerboard
    ports:
      - "5432:5432"