datasources:
    default:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        username: sa
flyway:
    datasources:
        default:
            enabled: true
micronaut:
    application:
        name: centerboardApi
netty:
    default:
        allocator:
            max-order: 3
