datasources:
    default:
        password: 'password'
        url: jdbc:postgresql://localhost:5432/centerboard
        username: centerboard
flyway:
    datasources:
        default:
            enabled: true
micronaut:
    application:
        name: centerboardApi
netty:
    default:
        allocator:
            max-order: 3
endpoints:
    health:
        details-visible: anonymous
