micronaut:
  application:
    name: toDoBackend
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    password: 'password'
    url: jdbc:postgresql://localhost:5432/to_do
    username: to_do
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
graphql:
    enabled: true
    path: /graphql
    graphiql:
        enabled: true
        path: /graphiql