micronaut:
  application:
    name: toDoBackend
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - ^http(|s):\/\/localhost:3000$
  http:
    services:
      github:
        url: 'https://api.github.com'

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    password: 'password'
    url: jdbc:postgresql://localhost:5432/to_do
    username: to_do
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
graphql:
    enabled: true
    path: /graphql
    graphiql:
        enabled: true
        path: /graphiql
github:
  organization: micronaut-projects
  repo: micronaut-core

team:
  name: 'Steelers'
  color: 'Black'
  player-names:
    - 'Mason Rudolph'
    - 'James Connor'
  team-admin:
    manager: 'Nirav Assar'
    coach: 'Mike Tomlin'
    president: 'Dan Rooney'

stadium:
  coors:
    city: 'Denver'
    size: 50000
  pnc:
    city: 'Pittsburgh'
    size: 35000